accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'

urlpatterns = [
	url(r'^home/$', views.home_view, name='home'),
	url(r'^signup/$', views.signup_view, name='signup'),
	url(r'^login/$', views.login_view, name='login'),
	url(r'^logout/$', views.logout_view, name='logout'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('accounts/', include('accounts.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
# from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # url(r'^$', views.IndexView.as_view(), name='index'),
    # url(r'^(?P<int:pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    # url(r'^(?P<int:pk>\d+)/results$', views.ResultsView.as_view(), name='results'),
    # url(r'^(?P<int:question_id>\d+)/vote$', views.vote, name='vote'),
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

accounts/models.py
from django.db import models

# Create your models here.

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.question_text

	def was_published_recently(self):
		now = timezone.now()
		# return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
		return now - datetime.timedelta(days=1) <= self.pub_date <= now
		was_published_recently.admin_order_field = 'pub_date'
		was_published_recently.boolean = True
		was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

accounts/views.py
from django.shortcuts import render, redirect
# from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def home_view(request):
	return render(request, 'accounts/home.html')

def signup_view(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			return redirect('accounts:login')

	else:
		form = UserCreationForm()
	return render(request, 'accounts/signup.html', {'form':form})

def login_view(request):
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			user = form.get_user()
			login(request, user)
			if 'next' in request.POST:
				return redirect(request.POST.get('next'))
			return redirect('polls:index')
	else:
		form = AuthenticationForm()
		
	return render(request, 'accounts/login.html',{'form':form})

def logout_view(request):
	if request.method == 'POST':
		logout(request)
		return redirect('accounts:login')

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
# from django.template import loader
# from django.http import Http404
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Question, Choice

# def index(request):
#     # return HttpResponse("Hello, world. You're at the polls index.")

# 	# latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     # output = ', '.join([q.question_text for q in latest_question_list])

# 	latest_question_list = Question.objects.order_by('-pub_date')[:5]
# 	# template = loader.get_template('polls/index.html')
# 	context = {
# 		'latest_question_list' : latest_question_list,
# 	}
# 	# return HttpResponse(template.render(context,request))

# 	return render(request, 'polls/index.html', context)

# def detail(request, question_id):
# 	# return HttpResponse("Question No. %s" % question_id)

# 	# try:
# 	# 	question = Question.objects.get(pk=question_id)
# 	# except Question.DoesNotExist:
# 	# 	raise Http404("Question does not exist")
# 	# return render(request, 'polls/detail.html',
# 	# 	{'question' : question})
# 	print(request.method)
# 	if request.method == "GET":
# 		question = get_object_or_404(Question, pk=question_id)
# 		return render(request, 'polls/detail.html',
# 			{'question' : question})

# 	else:
# 		pass

# def results(request, question_id):
# 	# response = "Results of question %s."
# 	# return HttpResponse(response % question_id)
# 	question = get_object_or_404(Question, pk=question_id)
# 	return render(request, 'polls/results.html', {'question' : question})

# <----------------GENERIC VIEW------------------------->
class IndexView(LoginRequiredMixin, generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'latest_question_list'

	def get_queryset(self):
		# return Question.objects.order_by('-pub_date')[:5]
		return Question.objects.filter(
			pub_date__lte=timezone.now()
			).order_by('-pub_date')[:5]

class DetailView(LoginRequiredMixin, generic.DetailView):
	model = Question
	template_name = 'polls/detail.html'

	def get_queryset(self):
		return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(LoginRequiredMixin, generic.DetailView):
	model = Question
	template_name = 'polls/results.html'	

@login_required(login_url='/accounts/login/')
def vote(request, question_id):
	# return HttpResponse("You voted question %s." % question_id)
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'polls/detail.html', {
			'question' : question, 
			'error_message' : "You did not select a choice",
			})
	else:
		selected_choice.votes += 1
		selected_choice.save()

		return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

accounts/templates/accounts/home.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'accounts/styles.css' %}" />

<!DOCTYPE html>
<html>
<head>
	<title>Django App</title>
</head>
<body>
	<h1>MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEP</h1>
	<br>
	<ul>
		<li><a href="{% url 'accounts:login' %}">Login</a></li>
		<li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
	</ul>
</body>
</html>

accounts/templates/accounts/login.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'accounts/styles.css' %}" />

{% block content %}
{% if next %}
	<p>Please login to see this page.</p>
{% endif %}

<h1>Login</h1>
<form class="site-form" action="{% url 'accounts:login' %}" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	{% if request.GET.next %}
		<input type="hidden" name="next" value="{{ request.GET.next }}">
	{% endif %}
	<input type="submit" value="Login">
</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'accounts/styles.css' %}" />

{% block content %}
<h1>Sign-up</h1>
<form class="site-form" action="/accounts/signup/" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Signup">
</form>

<a href="{% url 'accounts:login' %}">Login</a>
{% endblock %}

polls/templates/polls/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/styles.css' %}" />
<a href="{% url 'polls:index' %}">Back</a>
<form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
	{% csrf_token %}
	<button type="submit">Logout</button>
</form>
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
	<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}

<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/styles.css' %}" />

<ul class="sidebar-nav">
	{% if user.is_authenticated %}
		{% if latest_question_list %}
			<ul>
			{% for question in latest_question_list %}
				<!-- <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li> -->
				<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
			{% endfor %}
			</ul>
		{% else %}
			<p>No polls are available.</p>
		{% endif %}
		<br>
		<br>
		<form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
			{% csrf_token %}
			<button type="submit">Logout</button>
		</form>
	{% else %}
		<li><a href="{% url 'login' %}?next={{request.path}}">Login</a></li>
	{% endif %}
</ul>

polls/templates/polls/results.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/styles.css' %}" />

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
	<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize}}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Django App</title>
	<link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
	<header class="wrapper">
		<nav>
			<ul>
				<li>
					<form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
						{% csrf_token %}
						<button type="submit">Logout</button>
					</form>
				</li>
			</ul>
		</nav>
	</header>
</body>
</html>